photosocial/forms/user.py
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, TextAreaField, PasswordField, BooleanField, SubmitField, HiddenField, ValidationError
from wtforms.validators import DataRequired, Length, Email, EqualTo, Optional, Regexp

from photosocial.models import User


class EditProfileForm(FlaskForm):
    """资料表单"""
    name = StringField('昵称', validators=[DataRequired(), Length(1, 30)])
    username = StringField('用户名', validators=[DataRequired(), Length(1.20),
                                              Regexp('^[a-zA-Z0-9]*$', message='应为大小写字母和数字')])
    website = StringField('站点', validators=[Optional(), Length(0, 255)])
    location = StringField('位置', validators=[Optional(), Length(0, 50)])
    bio = TextAreaField('简介', validators=[Optional(), Length(0, 120)])
    submit = SubmitField('确定')

    # 为支持用户名更改，需要查询是否重复
    def validate_username(self, field):
        if field.data != current_user.username:
            if User.query.filter_by(userbame=field.data).first():
                raise ValidationError('这个名字已被使用')


class UploadAvatarForm(FlaskForm):
    """上传头像"""
    image = FileField('上传头像(<= 3M)',
                      validators=[FileRequired(), FileAllowed(['jpg', 'png'], '图片应为.jpg或者.png格式')])
    submit = SubmitField('确定')


class CropAvatarForm(FlaskForm):
    """裁剪头像"""
    x = HiddenField()
    y = HiddenField()
    w = HiddenField()
    h = HiddenField()
    submit = SubmitField('裁剪更新')


class ChangePasswordForm(FlaskForm):
    """更换密码"""
    old_password = StringField('原始密码', validators=[DataRequired()])
    password = StringField('新密码', validators=[DataRequired(), Length(8, 128), EqualTo('password2')])
    password2 = StringField('重复密码', validators=[DataRequired()])
    submit = SubmitField('确定')


class ChangeEmailForm(FlaskForm):
    """更换邮箱"""
    email = StringField('新邮箱', validators=[DataRequired(), Length(1, 254), Email()])
    submit = SubmitField('确定')


class NotificationSettingForm(FlaskForm):
    """消息提醒设置"""
    receive_comment_notification = BooleanField('新评论')
    receive_follow_notification = BooleanField('新粉丝')
    receive_collect_notification = BooleanField('新收藏')
    submit = SubmitField('确定')


class PrivacySettingForm(FlaskForm):
    """隐私设置"""
    public_collections = BooleanField('公开收藏')
    submit = SubmitField('确定')


class DeleteAccountForm(FlaskForm):
    """删除帐户"""
    username = StringField('用户名', validators=[DataRequired(), Length(1, 20)])
    submit = SubmitField('确定')

    # 验证眼删除用户的用户名与原来用户名是否一致
    def validate_username(self, field):
        if field.data != current_user.userrname:
            raise ValidationError('用户名错误')

photosocial/blueprints/user.py
from flask import Blueprint, render_template, flash, redirect, current_app, request, url_for
from flask_login import login_required, current_user, logout_user, fresh_login_required

from photosocial.models import User, Photo, Collect
from photosocial.decorators import confirm_required, permission_required
from photosocial.utils import redirect_back, generate_token, validate_token, flash_errors
from photosocial.notifications import push_follow_notification
from photosocial.forms.user import EditProfileForm, ChangePasswordForm, ChangeEmailForm, NotificationSettingForm, \
    PrivacySettingForm, DeleteAccountForm, UploadAvatarForm, CropAvatarForm
from photosocial.extensions import db, avatars
from photosocial.settings import Operations
from photosocial.emails import send_confirm_email

user_bp = Blueprint('user', __name__)


@user_bp.route('/<username>')
def index(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user == current_user and user.locked:
        flash('您的账号已被锁定.', 'danger')

    if user == current_user and not user.active:
        logout_user()

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_PHOTO_PER_PAGE']
    pagination = Photo.query.with_parent(user).order_by(Photo.timestamp.desc()).paginate(page, per_page)
    photos = pagination.items
    return render_template('user/index.html', user=user, pagination=pagination, photos=photos)


@user_bp.route('/<username>/collections')
def show_collections(username):
    """展示收藏"""
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_PHOTO_PER_PAGE']
    pagination = Collect.query.with_parent(user).order_by(Collect.timestamp.desc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('user/collections.html', user=user, pagination=pagination, collects=collects)


@user_bp.route('/follow/<username>', methods=['POST'])
@login_required
@permission_required('FOLLOW')
def follow(username):
    """关注"""
    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_followed(user):
        flash('已经关注过', 'info')
        return redirect(url_for('user.index', username=username))
    current_user.follow(user)
    if user.receive_follow_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return redirect_back()


@user_bp.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    """取消关注"""
    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_followed(user):
        flash('没有关注他', 'info')
        return redirect(url_for('user.index', username=username))
    current_user.unfollow(user)
    return redirect_back()


@user_bp.route('/<username>/following')
def show_following(username):
    """展示关注的人"""
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_USER_PER_PAGE']
    pagination = user.following.paginate(page, per_page)
    follows = pagination.items
    return render_template('user/following.html', user=user, pagination=pagination, follows=follows)


@user_bp.route('/<username>/followers')
def show_followed(username):
    """展示粉丝"""
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_USER_PER_PAGE']
    pagination = user.followers.paginate(page, per_page)
    follows = pagination.items
    return render_template('user/followers.html', user=user, pagination=pagination, follows=follows)


@user_bp.route('/settings/profile', methods=['GET', 'POST'])
@login_required
@confirm_required
def edit_profile():
    """编辑资料"""
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.username = form.username.data
        current_user.website = form.website.data
        current_user.location = form.location.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash('资料已更新', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    form.name.data = current_user.name
    form.username.data = current_user.username
    form.website.data = current_user.website
    form.location.data = current_user.location
    form.bio.data = current_user.bio
    return render_template('user/settings/edit_profile.html', form=form)


@user_bp.route('/settings/avatar')
@login_required
@confirm_required
def change_avatar():
    """更换头像"""
    upload_form = UploadAvatarForm()
    crop_form = CropAvatarForm()
    return render_template('user/settings/change_avatar.html', upload_form=upload_form, crop_form=crop_form)


@user_bp.route('/settings/avatar/upload', methods=['POST'])
@login_required
@confirm_required
def upload_avatar():
    """上传头像"""
    form = UploadAvatarForm()
    if form.validate_on_submit():
        image = form.image.data  # 获取文件数据
        filename = avatars.save_avatar(image)  # avatars.save_avatar会自动处理文件名，并保存到配置变量AVATARS_SAVE_PATH路径下
        current_user.avatar_raw = filename  # 返回文件名
        db.session.commit()
        flash('图片上传成功，请裁剪', 'success')
    flash_errors(form)
    return redirect(url_for('user.change_avatar'))


@user_bp.route('/settings/avatar/crop', methods=['POST'])
@login_required
@confirm_required
def crop_avatar():
    """裁剪头像"""
    form = CropAvatarForm()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        # avatars.crop_avatar会按照配置AVATARS_SIZE_TUPLE中的设置裁剪出三种尺寸的文件，然后按小到大排列
        filenames = avatars.crop_avatar(current_user.avatar_raw, x, y, w, h)
        current_user.avatar_s = filenames[0]
        current_user.avatar_m = filenames[1]
        current_user.avatar_l = filenames[2]
        db.session.commit()
        flash('头像更新成功', 'success')
    flash_errors(form)
    return redirect(url_for('user.change_avatar'))


@user_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required   # 确保用户处于‘活跃’状态
@confirm_required
def change_password():
    """更换密码"""
    form = ChangePasswordForm()
    # 当表单通过验证并且旧密码也通过验证的时候
    if form.validate_on_submit() and current_user.validate_password(form.old_password.data):
        current_user.set_password(form.password.data)
        db.session.commit()
        flash('密码重置成功', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    return render_template('user/settings/change_password.html', form=form)


@user_bp.route('/settings/change-email', methods=['GET', 'POST'])
@fresh_login_required
@confirm_required
def change_email_request():
    """发送更换邮箱验证邮件"""
    form = ChangeEmailForm()
    if form.validate_on_submit():
        # 创建令牌
        token = generate_token(user=current_user, operation=Operations.CHANGE_EMAIL, new_email=form.email.data.lower())
        send_confirm_email(to=form.email.data, user=current_user, token=token)
        flash('验证邮件已经发送，请查看邮箱', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    return render_template('user/settings/change_email.html', form=form)


@user_bp.route('/change-email/<token>')
@login_required
@confirm_required
def change_email(token):
    """绑定新邮箱"""
    if validate_token(user=current_user, token=token, operation=Operations.CHANGE_EMAIL):
        flash('邮箱已更新', 'success')
        return redirect(url_for('user.index', userame=current_user.username))
    else:
        flash('无效或过期令牌', 'warning')
        return redirect(url_for('user.change_email_request'))


@user_bp.route('/settings/notification', methods=['GET', 'POST'])
@login_required
@confirm_required
def notification_setting():
    """消息提醒设置"""
    form = NotificationSettingForm()
    if form.validate_on_submit():
        current_user.receive_comment_notification = form.receive_comment_notification.data
        current_user.receive_collect_notification = form.receive_collect_notification.data
        current_user.receive_follow_notification = form.receive_follow_notification.data
        db.session.commit()
        flash('消息提醒设置已更新', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    form.receive_collect_notification.data = current_user.receive_collect_notification
    form.receive_comment_notification.data = current_user.receive_comment_notification
    form.receive_follow_notification.data = current_user.receive_follow_notification
    return render_template('user/settings/edit_notification.html', form=form)


@user_bp.route('/settings/privacy', methods=['GET', 'POST'])
@login_required
@confirm_required
def privacy_setting():
    """收藏隐私"""
    form = PrivacySettingForm()
    if form.validate_on_submit():
        current_user.public_collections = form.public_collections.data
        db.session.commit()
        flash('收藏隐私更新', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    form.public_collections.data = current_user.public_collections
    return render_template('user/settings/edit_privacy.html', form=form)


@user_bp.route('/settings/account/delete', methods=['GET', 'POST'])
@fresh_login_required
def delete_account():
    """删除帐户"""
    form = DeleteAccountForm()
    if form.validate_on_submit():
        db.session.delete(current_user._get_current_object())
        db.session.commit()
        flash('您是自由的，再见！', 'success')
        return redirect('main.index')
    return render_template('user/settings/delete_account.html', form=form)

photosocial/templates/user/settings/base.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/nav.html' import render_nav_item %}

{% block content %}
    <div class="page-header">
        <h1>设置</h1>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="nav nav-pills flex-column">
                {{ render_nav_item('user.edit_profile','编辑资料') }}
                {{ render_nav_item('user.change_avatar','更改头像') }}
                {{ render_nav_item('user.change_password','更改密码') }}
                {{ render_nav_item('user.change_email_request','更改邮箱') }}
                {{ render_nav_item('user.notification_setting','消息设置') }}
                {{ render_nav_item('user.privacy_setting','隐私设置') }}
                {{ render_nav_item('user.delete_account','注销帐户') }}
            </div>
        </div>
        <div class="col-md-9">
            {% block setting_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

photosocial/templates/user/settings/change_avatar.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Change Avatar{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static',filename='jcrop/css/jquery.Jcrop.min.css') }}">
{% endblock %}

{% block setting_content %}
    <div class="card bg-light w-100">
        <h3 class="card-header">更换头像</h3>
        <div class="card-body">
            {{ render_form(upload_form, action=url_for('user.upload_avatar')) }}
            <small class="text-muted">图片大小不应超过3M，格式为.jpg或者.png</small>
        </div>
        <div class="card-body">
            {{ avatars.crop_box('main.get_avatar',current_user.avatar_raw) }}  # 渲染裁剪窗口
            {{ avatars.preview_box('main.get_avatar',current_user.avatar_raw) }}  # 渲染预览窗口
        </div>
        <div class="card-body">
            {{ render_form(crop_form, action=url_for('user.crop_avatar')) }}
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ super() }}
    <script src="{{ url_for('static',filename='jcrop/js/jquery.Jcrop.min.js') }}"></script>
    {{ avatars.init_jcrop() }}  # 初始化Jcrop
{% endblock %}

photosocial/templates/user/settings/change_email.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Change Email{% endblock %}

{% block setting_content %}
    <div class="card bg-light w-100">
        <h3 class="card-header">更换邮箱</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

photosocial/templates/user/settings/change_password.html
{% extends 'user/settings/base.html'%}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Change Password{% endblock %}

{% block setting_content %}
    <div class="card bg-light w-100">
        <h3 class="card-header">更换密码</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

photosocial/templates/user/settings/delete_account.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Delete Account{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light border-danger">
        <h3 class="card-header">删除用户</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

photosocial/templates/user/settings/edit_notification.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Notification Settings{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">消息提醒设置</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

photosocial/templates/user/settings/edit_privacy.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Privacy Settings{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">隐私设置</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

photosocial/templates/user/settings/edit_profile.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Edit Profile{% endblock %}
{% block setting_content %}
    <div class="card bg-light w-100">
        <h3 class="card-header">编辑资料</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}