photosocial/blueprints/admin.py
import os

from flask import Blueprint, flash, render_template, redirect, url_for, request, current_app
from flask_login import login_required

from photosocial.extensions import db
from photosocial.models import User, Role, Tag, Photo, Comment
from photosocial.decorators import permission_required, admin_required
from photosocial.utils import redirect_back
from photosocial.forms.admin import EditProfileAdminForm

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/')
@login_required
@permission_required('MODERATE')
def index():
    photo_count = Photo.query.count()
    reported_photos_count = Photo.query.filter(Photo.flag > 0).count()
    user_count = User.query.count()
    locked_user_count = User.query.filter_by(locked=True).count()
    blocked_user_count = User.query.filter_by(active=False).count()
    tag_count = Tag.query.count()
    comment_count = Comment.query.count()
    reported_comments_count = Comment.query.filter(Comment.flag > 0).count()
    return render_template('admin/index.html', photo_count=photo_count, reported_photos_count=reported_photos_count,
                           user_count=user_count, locked_user_count=locked_user_count,
                           block_user_count=blocked_user_count, tag_count=tag_count, comment_count=comment_count,
                           reported_comments_count=reported_comments_count)


@admin_bp.route('/lock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def lock_user(user_id):
    """用户锁定"""
    user = User.query.get_or_404(user_id)
    user.lock()
    flash('该用户已锁定', 'info')
    return redirect_back()


@admin_bp.route('/unlock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unlock_user(user_id):
    """解除用户锁定"""
    user = User.query.get_or_404(user_id)
    user.unlock()
    flash('该用户锁定解除', 'info')
    return redirect_back()


@admin_bp.route('/block/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def block_user(user_id):
    """封禁用户"""
    user = User.query.get_or_404(user_id)
    user.block()
    flash('用户已封禁', 'info')
    return redirect_back()


@admin_bp.route('/unblock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unblock_user(user_id):
    """解除用户封禁"""
    user = User.query.get_or_404(user_id)
    user.unblock()
    flash('用户封禁已解除', 'info')
    return redirect_back()


@admin_bp.route('/profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(user_id):
    """管理员编辑用户资料"""
    user = User.query.get_or_404(user_id)
    form = EditProfileAdminForm(user=user)  # 传入被修改的用户对象作为参数
    if form.validate_on_submit():
        user.name = form.name.data
        role = Role.query.get(form.role.data)
        if role.name == 'Locked':
            user.lock()
        user.role = role
        user.username = form.username.data
        user.email = form.email.data
        user.website = form.website.data
        user.location = form.location.data
        user.bio = form.bio.data
        user.active = form.active.data
        user.confirmed = form.confirmed.data
        db.session.commit()
        flash('更新', 'success')
        return redirect_back()
    form.name.data = user.name
    form.role.data = user.role_id
    form.username.data = user.username
    form.email.data = user.email
    form.website.data = user.website
    form.location.data = user.location
    form.bio.data = user.bio
    form.active.data = user.active
    form.confirmed.data = user.confirmed
    return render_template('admin/edit_profile.html', form=form, user=user)


@admin_bp.route('/manage/photo', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/photo/<order>')
@login_required
@permission_required('MODERATE')
def manage_photo(order):
    """管理图片"""
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_MANAGE_PHOTO_PER_PAGE']
    order_rule = '被举报次数'
    if order == 'by_time':
        pagination = Photo.query.order_by(Photo.timestamp.desc()).paginate(page, per_page)
        order_rule = '时间'
    else:
        pagination = Photo.query.order_by(Photo.flag.desc()).paginate(page, per_page)
    photos = pagination.items
    return render_template('admin/manage_photo.html', photos=photos, pagination=pagination, order_rule=order_rule)


@admin_bp.route('/manage/user')
@login_required
@permission_required('MODERATE')
def manage_user():
    """管理用户"""
    filter_rule = request.args.get('filter', 'all')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_MANAGE_USER_PER_PAGE']
    moderator = Role.query.filter_by(name='Moderator').first()

    if filter_rule == 'locked':
        filtered_users = User.query.filter_by(locked=True)
    elif filter_rule == 'blocked':
        filtered_users = User.query.filter_by(active=False)
    elif filter_rule == 'moderator':
        filtered_users = User.query.filter_by(role=moderator)
    else:
        filtered_users = User.query

    pagination = filtered_users.order_by(User.member_since.desc()).paginate(page, per_page)
    users = pagination.items
    return render_template('admin/manage_user.html', pagination=pagination, users=users)


@admin_bp.route('/manage/tag')
@login_required
@permission_required('MODERATE')
def manage_tag():
    """管理标签"""
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_MANAGE_TAG_PER_PAGE']
    pagination = Tag.query.order_by(Tag.id.desc()).paginate(page, per_page)
    tags = pagination.items
    return render_template('admin/manage_tag.html', pagination=pagination, tags=tags)


@admin_bp.route('/delete/tag/<int:tag_id>', methods=['GET', 'POST'])
@login_required
@permission_required('MODERATE')
def delete_tag(tag_id):
    """删除标签"""
    tag = Tag.query.get_or_404(tag_id)
    db.session.delete(tag)
    db.session.commit()
    flash('Tag deleted.', 'info')
    return redirect_back()


@admin_bp.route('/manage/comment', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/comment/<order>')
@login_required
@permission_required('MODERATE')
def manage_comment(order):
    """管理评论"""
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_MANAGE_COMMENT_PER_PAGE']
    order_rule = '被举报次数'
    if order == 'by_time':
        pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(page, per_page)
        order_rule = '时间'
    else:
        pagination = Comment.query.order_by(Comment.flag.desc()).paginate(page, per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', pagination=pagination, order_rule=order_rule, comments=comments)

photosocial/blueprints/user.py
from flask import Blueprint, render_template, flash, redirect, current_app, request, url_for
from flask_login import login_required, current_user, logout_user, fresh_login_required

from photosocial.models import User, Photo, Collect
from photosocial.decorators import confirm_required, permission_required
from photosocial.utils import redirect_back, generate_token, validate_token, flash_errors
from photosocial.notifications import push_follow_notification
from photosocial.forms.user import EditProfileForm, ChangePasswordForm, ChangeEmailForm, NotificationSettingForm, \
    PrivacySettingForm, DeleteAccountForm, UploadAvatarForm, CropAvatarForm
from photosocial.extensions import db, avatars
from photosocial.settings import Operations
from photosocial.emails import send_confirm_email

user_bp = Blueprint('user', __name__)


@user_bp.route('/<username>')
def index(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user == current_user and user.locked:
        flash('您的账号已被锁定.', 'danger')

    if user == current_user and not user.active:
        logout_user()

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_PHOTO_PER_PAGE']
    pagination = Photo.query.with_parent(user).order_by(Photo.timestamp.desc()).paginate(page, per_page)
    photos = pagination.items
    return render_template('user/index.html', user=user, pagination=pagination, photos=photos)


@user_bp.route('/<username>/collections')
def show_collections(username):
    """展示收藏"""
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_PHOTO_PER_PAGE']
    pagination = Collect.query.with_parent(user).order_by(Collect.timestamp.desc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('user/collections.html', user=user, pagination=pagination, collects=collects)


@user_bp.route('/follow/<username>', methods=['POST'])
@login_required
@permission_required('FOLLOW')
def follow(username):
    """关注"""
    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_followed(user):
        flash('已经关注过', 'info')
        return redirect(url_for('user.index', username=username))
    current_user.follow(user)
    if user.receive_follow_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return redirect_back()


@user_bp.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    """取消关注"""
    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_followed(user):
        flash('没有关注他', 'info')
        return redirect(url_for('user.index', username=username))
    current_user.unfollow(user)
    return redirect_back()


@user_bp.route('/<username>/following')
def show_following(username):
    """展示关注的人"""
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_USER_PER_PAGE']
    pagination = user.following.paginate(page, per_page)
    follows = pagination.items
    return render_template('user/following.html', user=user, pagination=pagination, follows=follows)


@user_bp.route('/<username>/followers')
def show_followed(username):
    """展示粉丝"""
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_USER_PER_PAGE']
    pagination = user.followers.paginate(page, per_page)
    follows = pagination.items
    return render_template('user/followers.html', user=user, pagination=pagination, follows=follows)


@user_bp.route('/settings/profile', methods=['GET', 'POST'])
@login_required
@confirm_required
def edit_profile():
    """编辑资料"""
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.username = form.username.data
        current_user.website = form.website.data
        current_user.location = form.location.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash('资料已更新', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    form.name.data = current_user.name
    form.username.data = current_user.username
    form.website.data = current_user.website
    form.location.data = current_user.location
    form.bio.data = current_user.bio
    return render_template('user/settings/edit_profile.html', form=form)


@user_bp.route('/settings/avatar')
@login_required
@confirm_required
def change_avatar():
    """更换头像"""
    upload_form = UploadAvatarForm()
    crop_form = CropAvatarForm()
    return render_template('user/settings/change_avatar.html', upload_form=upload_form, crop_form=crop_form)


@user_bp.route('/settings/avatar/upload', methods=['POST'])
@login_required
@confirm_required
def upload_avatar():
    """上传头像"""
    form = UploadAvatarForm()
    if form.validate_on_submit():
        image = form.image.data  # 获取文件数据
        filename = avatars.save_avatar(image)  # avatars.save_avatar会自动处理文件名，并保存到配置变量AVATARS_SAVE_PATH路径下
        current_user.avatar_raw = filename  # 返回文件名
        db.session.commit()
        flash('图片上传成功，请裁剪', 'success')
    flash_errors(form)
    return redirect(url_for('user.change_avatar'))


@user_bp.route('/settings/avatar/crop', methods=['POST'])
@login_required
@confirm_required
def crop_avatar():
    """裁剪头像"""
    form = CropAvatarForm()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        # avatars.crop_avatar会按照配置AVATARS_SIZE_TUPLE中的设置裁剪出三种尺寸的文件，然后按小到大排列
        filenames = avatars.crop_avatar(current_user.avatar_raw, x, y, w, h)
        current_user.avatar_s = filenames[0]
        current_user.avatar_m = filenames[1]
        current_user.avatar_l = filenames[2]
        db.session.commit()
        flash('头像更新成功', 'success')
    flash_errors(form)
    return redirect(url_for('user.change_avatar'))


@user_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required   # 确保用户处于‘活跃’状态
@confirm_required
def change_password():
    """更换密码"""
    form = ChangePasswordForm()
    # 当表单通过验证并且旧密码也通过验证的时候
    if form.validate_on_submit() and current_user.validate_password(form.old_password.data):
        current_user.set_password(form.password.data)
        db.session.commit()
        flash('密码重置成功', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    return render_template('user/settings/change_password.html', form=form)


@user_bp.route('/settings/change-email', methods=['GET', 'POST'])
@fresh_login_required
@confirm_required
def change_email_request():
    """发送更换邮箱验证邮件"""
    form = ChangeEmailForm()
    if form.validate_on_submit():
        # 创建令牌
        token = generate_token(user=current_user, operation=Operations.CHANGE_EMAIL, new_email=form.email.data.lower())
        send_confirm_email(to=form.email.data, user=current_user, token=token)
        flash('验证邮件已经发送，请查看邮箱', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    return render_template('user/settings/change_email.html', form=form)


@user_bp.route('/change-email/<token>')
@login_required
@confirm_required
def change_email(token):
    """绑定新邮箱"""
    if validate_token(user=current_user, token=token, operation=Operations.CHANGE_EMAIL):
        flash('邮箱已更新', 'success')
        return redirect(url_for('user.index', userame=current_user.username))
    else:
        flash('无效或过期令牌', 'warning')
        return redirect(url_for('user.change_email_request'))


@user_bp.route('/settings/notification', methods=['GET', 'POST'])
@login_required
@confirm_required
def notification_setting():
    """消息提醒设置"""
    form = NotificationSettingForm()
    if form.validate_on_submit():
        current_user.receive_comment_notification = form.receive_comment_notification.data
        current_user.receive_collect_notification = form.receive_collect_notification.data
        current_user.receive_follow_notification = form.receive_follow_notification.data
        db.session.commit()
        flash('消息提醒设置已更新', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    form.receive_collect_notification.data = current_user.receive_collect_notification
    form.receive_comment_notification.data = current_user.receive_comment_notification
    form.receive_follow_notification.data = current_user.receive_follow_notification
    return render_template('user/settings/edit_notification.html', form=form)


@user_bp.route('/settings/privacy', methods=['GET', 'POST'])
@login_required
@confirm_required
def privacy_setting():
    """收藏隐私"""
    form = PrivacySettingForm()
    if form.validate_on_submit():
        current_user.public_collections = form.public_collections.data
        db.session.commit()
        flash('收藏隐私更新', 'success')
        return redirect(url_for('user.index', username=current_user.username))
    form.public_collections.data = current_user.public_collections
    return render_template('user/settings/edit_privacy.html', form=form)


@user_bp.route('/settings/account/delete', methods=['GET', 'POST'])
@fresh_login_required
def delete_account():
    """删除帐户"""
    form = DeleteAccountForm()
    if form.validate_on_submit():
        db.session.delete(current_user._get_current_object())
        db.session.commit()
        flash('您是自由的，再见！', 'success')
        return redirect('main.index')
    return render_template('user/settings/delete_account.html', form=form)

photosocial/templates/user/_header.html
{% from 'bootstrap/nav.html' import render_nav_item %}
{% from 'macros.html' import follow_area with context %}

<div class="row">
    <div class="col-md-3">
        <a href="{% if current_user == user %}{{ url_for('.change_avatar') }}{% else %}#{% endif %}"
           title="Change avatar">
            <img class="img-fluid rounded" src="{{ url_for('main.get_avatar',filename=user.avatar_l) }}">
        </a>
    </div>
    <div class="col-md-9">
        <h1>{{ user.name }}
            <small class="text-muted">{{ user.username }}</small>
        </h1>
        {% if user.bio %}{{ user.bio }}{% endif %}
        <p>
            {% if user.website %}
                <span class="oi oi-link-intact"></span>
                <a href="{{ user.website }}" target="_blank">{{ user.website|truncate(30) }}</a>&nbsp;&nbsp;
            {% endif %}
            {% if user.location %}
                <span class="oi oi-map-marker"></span>
                <a href="https://google.com/maps?q={{ user.location }}">{{ user.location|truncate(20) }}</a>&nbsp;&nbsp;
            {% endif %}
            <span class="oi oi-calendar"></span>
            加入 {{ moment(user.member_since).format('LL') }}
        </p>
        <div>
            {% if current_user != user %}
                {% if current_user.can('MODERATE') %}
                    {% if not user.can('ADMINISTER') %}
                        {% if user.locked %} <!--显示解除锁定-->
                            <form class="inline" method="post" action="{{ url_for('admin.unlock_user',user_id=user.id) }}">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <button type="submit" class="btn btn-secondary btn-sm">
                                    解除锁定 <span class="oi oi-lock-locked"></span>
                                </button>
                            </form>
                        {% else %} <!--显示锁定-->
                            <form class="inline" method="post" action="{{ url_for('admin.lock_user',user_id=user.id) }}">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <button type="submit" class="btn btn-warning btn-sm">锁定</button>
                            </form>
                        {% endif %}
                        {% if user.active %}
                            <form class="inline" method="post" action="{{ url_for('admin.block_user',user_id=user.id) }}">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <button type="submit" class="btn btn-warning btn-sm">封禁</button>
                            </form>
                        {% else %}
                            <form class="inline" method="post" action="{{ url_for('admin.unblock_user',user_id=user.id) }}">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <button type="submit" class="btn btn-secondary btn-sm">
                                    解除封禁 <span class="oi oi-circle-x"></span>
                                </button>
                            </form>
                        {% endif %}
                        <a class="btn btn-outline-primary btn-sm" href="mailto:{{ user.email }}">Email</a>
                    {% endif %}
                {% endif %}
                {% if current_user.is_admin %}
                    <a class="btn btn-warning btn-sm" href="{{ url_for('admin.edit_profile_admin',user_id=user.id) }}">
                        编辑用户
                    </a>
                {% endif %}
            {% endif %}
            <div class="float-right">
                {{ follow_area(user) }}
                {% if current_user.is_authenticated and user == current_user %}
                    <a class="btn btn-outline-primary btn-sm" href="{{ url_for('user.edit_profile') }}">
                        编辑资料
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="user-nav">
    <ul class="nav nav-tabs">
        <!--额外传入的关键字参数username会被传入url_for-->
        {{ render_nav_item('user.index', '图片', user.photos|length, username=user.username,candelete='photo') }}
        {{ render_nav_item('user.show_collections','收藏',user.collections|length,username=user.username,candelete='collect') }}
        <!-- 因为自己关注了自己，但不需要在关注、粉丝界面显示自己，所以数量减一 -->
        {{ render_nav_item('user.show_following','关注',user.following.count()-1,username=user.username) }}
        {{ render_nav_item('user.show_followed','粉丝',user.followers.count()-1,username=user.username) }}
    </ul>
</div>

photosocial/templates/user/collections.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card %}

{% block title %}{{ user.name}}'s collections{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if user.public_collections or current_user==user %}
                {% if collects %}
                    {% for collect in collects %}
                        {{ photo_card(collect.collected) }}
                    {% endfor %}
                {% else %}
                    <div class="tip">
                        <h3>没有收藏</h3>
                        <a href="{{ url_for('main.explore') }}">去转转</a>
                    </div>
                {% endif %}
            {% else %}
                <div class="tip">
                    <h3>该用户的收藏仅自己可见...</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if collects %}
        <div class="page-footer">
            {{ render_pagination(pagination,align='center') }}
        </div>
    {% endif %}
{% endblock%}

photosocial/templates/user/followers.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}{{ user.name}}'followers{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if follows|length != 1 %}
                {% for follow in follows %}
                    {% if follow.follower != user %}
                        {{ user_card(user=follow.follower) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h3>没有粉丝...</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if follows|length != 1 %}
        <div class="page-footer">
            {{ render_pagination(pagination,align="center") }}
        </div>
    {% endif %}
{% endblock %}

photosocial/templates/user/following.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}{{ user.name}}'following{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if follows|length != 1 %}
                {% for follow in follows %}
                    {% if follow.followed != user %}
                        {{ user_card(user=follow.followed) }}
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="tip">
                    <h3>没有关注的人...</h3>
                </div>
            {% endif %}
        </div>
    </div>
    {% if follows|length %}
        <div class="page-footer">
            {{ render_pagination(pagination,align="center") }}
        </div>
    {% endif %}
{% endblock %}

photosocial/templates/user/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card %}

{% block title %}{{ user.name }}{% endblock %}

{% block content %}
    {% include 'user/_header.html' %}
    <div class="row">
        <div class="col-md-12">
            {% if photos %}
                {% for photo in photos %}
                    {{ photo_card(photo) }}
                {% endfor %}
            {% else %}
                <div class="tip text-center">
                    <h3>图片溜走了...</h3>
                    {% if user == current_user %} <!--若果是用户个人主页，显示上传-->
                        <a class="btn btn-link" href="{{ url_for('main.upload') }}">上传</a>
                    {% else %} <!--否则，显示发现-->
                        <a class="btn btn-link" href="{{ url_for('main.explore') }}">发现</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
    {% if photos %}
        <div class="page-footer">
            {{ render_pagination(pagination, align='center') }}
        </div>
    {% endif %}
{% endblock %}