photosocial/forms/main.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, Optional


class DescriptionForm(FlaskForm):
    """图片描述表单"""
    description = TextAreaField('图片描述', validators=[Optional(), Length(0, 500)])
    submit = SubmitField('确定')


class TagForm(FlaskForm):
    tag = StringField('添加标签(使用空格分隔可以添加多个标签)', validators=[Optional(), Length(0, 64)])
    submit = SubmitField('确定')


class CommentForm(FlaskForm):
    body = TextAreaField('', validators=[DataRequired()])
    submit = SubmitField('确定')

photosocial/blueprints/ajax.py
from flask import Blueprint, render_template, jsonify
from flask_login import current_user

from photosocial.models import User, Photo, Notification
from photosocial.notifications import push_collect_notification, push_follow_notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    """返回用户资料"""
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/collectors-count/<int:photo_id>')
def collectors_count(photo_id):
    """图片收藏者数量"""
    photo = Photo.query.get_or_404(photo_id)
    count = len(photo.collectors)
    return jsonify(count=count)


@ajax_bp.route('/notifications-count')
def notifications_count():
    """未读消息数量"""
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)


@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    """粉丝数量"""
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1  # 减去自己
    return jsonify(count=count)


@ajax_bp.route('/collect/<int:photo_id>', methods=['POST'])
def collect(photo_id):
    """收藏"""
    if not current_user.is_authenticated:
        return jsonify(message='请先登陆.'), 403
    if not current_user.confirmed:
        return jsonify(message='请先验证邮箱.'), 400
    if not current_user.can('COLLECT'):
        return jsonify(message='没有权限.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if current_user.is_collecting(photo):
        return jsonify(message='已经收藏过.'), 400

    current_user.collect(photo)
    if current_user != photo.author and photo.author.receive_collect_notification:
        push_collect_notification(collector=current_user, photo_id=photo_id, receiver=photo.author)
    return jsonify(message='收藏成功.')


@ajax_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
def uncollect(photo_id):
    """取消收藏"""
    if not current_user.is_authenticated:
        return jsonify(message='请先登陆.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if not current_user.is_collecting(photo):
        return jsonify(message='没有收藏过.'), 400

    current_user.uncollect(photo)
    return jsonify(message='收藏取消.')


@ajax_bp.route('/follow/<username>', methods=['POST'])
def follow(username):
    """关注"""
    if not current_user.is_authenticated:
        return jsonify(message='请先登录.'), 403  # jsonify生成json相应格式，并返回提示消息
    if not current_user.confirmed:
        return jsonify(message='请先验证邮箱.'), 400
    if not current_user.can('FOLLOW'):
        return jsonify(message='没有权限.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_followed(user):
        return jsonify(message='已经关注过.'), 400

    current_user.follow(user)
    if user.receive_collect_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return jsonify(message='关注成功.')


@ajax_bp.route('/unfollow/<username>', methods=['POST'])
def unfollow(username):
    """取消关注"""
    if not current_user.is_authenticated:
        return jsonify(message='请先登陆.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_followed(user):
        return jsonify(message='还没有关注他/她.'), 400

    current_user.unfollow(user)
    return jsonify(message='关注取消.')

photosocial/blueprints/main.py
import os

from flask import Blueprint, render_template, redirect, url_for, request, flash, abort, \
    current_app, send_from_directory
from flask_login import current_user, login_required
from sqlalchemy.sql.expression import func

from photosocial.extensions import db
from photosocial.models import Photo, Tag, Comment, Collect, Notification, Follow, User
from photosocial.decorators import permission_required, confirm_required
from photosocial.utils import rename_image, resize_image, redirect_back, flash_errors
from photosocial.forms.main import DescriptionForm, TagForm, CommentForm
from photosocial.notifications import push_collect_notification, push_comment_notification

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['PHOTOSOCIAL_PHOTO_PER_PAGE']
        # .join()联结查询
        pagination = Photo.query \
            .join(Follow, Follow.followed_id == Photo.author_id) \
            .filter(Follow.follower_id == current_user.id) \
            .order_by(Photo.timestamp.desc()) \
            .paginate(page, per_page)
        photos = pagination.items
    else:
        pagination = None
        photos = None
    tags = Tag.query.join(Tag.photos).group_by(Tag.id).order_by(func.count(Photo.id).desc()).limit(10)
    return render_template('main/index.html', pagination=pagination, photos=photos, tags=tags, Collect=Collect)


@main_bp.route('/explore')
def explore():
    """发现界面"""
    photos = Photo.query.order_by(func.random()).limit(9)
    return render_template('main/explore.html', photos=photos)


@main_bp.route('/about')
def about():
    """关于界面"""
    return render_template('main/about.html')


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required  # 验证登陆状态
@permission_required('UPLOAD')  # 验证权限
def upload():
    """上传图片"""
    if request.method == 'POST' and 'file' in request.files:
        f = request.files.get('file')  # 获取文件图片对象
        filename = rename_image(f.filename)  # 生成随机文件名
        f.save(os.path.join(current_app.config['PHOTOSOCIAL_UPLOAD_PATH'], filename))  # 保存图片
        filename_s = resize_image(f, filename, current_app.config['PHOTOSOCIAL_PHOTO_SIZE']['small'])
        filename_m = resize_image(f, filename, current_app.config['PHOTOSOCIAL_PHOTO_SIZE']['medium'])
        photo = Photo(
            filename=filename,
            filename_s=filename_s,
            filename_m=filename_m,
            author=current_user._get_current_object()
        )
        db.session.add(photo)
        db.session.commit()
    return render_template('main/upload.html')


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    """获取头像"""
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/image/<path:filename>')
def get_image(filename):
    """获取图片"""
    return send_from_directory(current_app.config['PHOTOSOCIAL_UPLOAD_PATH'], filename)


@main_bp.route('/photo/<int:photo_id>')
def show_photo(photo_id):
    """展示图片"""
    photo = Photo.query.get_or_404(photo_id)

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(photo).order_by(Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items

    # 图片描述
    description_form = DescriptionForm()
    description_form.description.data = photo.description

    tag_form = TagForm()
    comment_form = CommentForm()

    return render_template('main/photo.html', photo=photo, comments=comments, description_form=description_form,
                           tag_form=tag_form, comment_form=comment_form, pagination=pagination)


@main_bp.route('/photo/n/<int:photo_id>')
def photo_next(photo_id):
    """下一张图片"""
    photo = Photo.query.get_or_404(photo_id)
    photo_n = Photo.query.with_parent(photo.author).filter(Photo.id < photo_id).order_by(Photo.id.desc()).first()
    if photo_n is None:
        flash('已经是最后一张图片', 'info')
        return redirect(url_for('main.show_photo', photo_id=photo.id))
    return redirect(url_for('main.show_photo', photo_id=photo_n.id))


@main_bp.route('/photo/p/<int:photo_id>')
def photo_previous(photo_id):
    """上一张图片"""
    photo = Photo.query.get_or_404(photo_id)
    photo_p = Photo.query.with_parent(photo.author).filter(Photo.id > photo_id).order_by(Photo.id.asc()).first()
    if photo_p is None:
        flash('已经是第一张了', 'info')
        return redirect(url_for('main.show_photo', photo_id=photo.id))
    return redirect(url_for('main.show_photo', photo_id=photo_p.id))


@main_bp.route('/delete/photo/<int:photo_id>', methods=['POST'])
@login_required
def delete_photo(photo_id):
    """删除图片"""
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author and not current_user.can('MODERATE'):
        abort(403)  # 如果不是作者本人或者不拥有管理员权限，则返回（403）错误

    db.session.delete(photo)
    db.session.commit()
    flash('图片删除', 'info')

    photo_n = Photo.query.with_parent(photo.author).filter(Photo.id < photo_id).order_by(Photo.id.desc()).first()
    if request.args.get('candelete') == 'photo':
        return redirect(url_for('user.index', username=photo.author.username))
    else:
        if photo_n is None:  # 如果没有下一张图片则寻找上一张
            photo_p = Photo.query.with_parent(photo.author).filter(Photo.id > photo_id).order_by(Photo.id.asc()).first()
            if photo_p is None:  # 如果没有上一张，返回用户主页
                return redirect(url_for('user.index', username=photo.author.username))
            return redirect(url_for('main.show_photo', photo_id=photo_p.id))
        return redirect(url_for('main.show_photo', photo_id=photo_n.id))


@main_bp.route('/report/photo/<int:photo_id>', methods=['POST'])
@login_required
@confirm_required
def report_photo(photo_id):
    """举报图片函数"""
    photo = Photo.query.get_or_404(photo_id)
    photo.flag += 1
    db.session.commit()
    flash('举报成功', 'success')
    return redirect(url_for('main.show_photo', photo_id=photo.id))


@main_bp.route('/photo/<int:photo_id>/description', methods=['GET', 'POST'])
@login_required
def edit_description(photo_id):
    """编辑图片描述"""
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author and not current_user.can('MODERATE'):
        abort(403)

    form = DescriptionForm()
    if form.validate_on_submit():
        photo.description = form.description.data
        db.session.commit()
        flash('图片描述更新成功', 'success')

    flash_errors(form)
    return redirect(url_for('main.show_photo', photo_id=photo.id))


@main_bp.route('/photo/<int:photo_id>/tag/new', methods=['POST'])
@login_required
def new_tag(photo_id):
    """添加标签"""
    photo = Photo.query.get_or_404(photo_id)
    if current_user != photo.author:
        abort(403)

    form = TagForm()
    if form.validate_on_submit():
        for name in form.tag.data.split():
            tag = Tag.query.filter_by(name=name).first()
            if tag is None:  # 如果标签不存在，则添加
                tag = Tag(name=name)
                db.session.add(tag)
                db.session.commit()
            if tag not in photo.tags:
                photo.tags.append(tag)
                db.session.commit()
        flash('标签添加成功', 'success')

    flash_errors(form)
    return redirect(url_for('main.show_photo', photo_id=photo.id))


@main_bp.route('/delete/tag/<int:photo_id>/<int:tag_id>', methods=['POST'])
@login_required
def delete_tag(photo_id, tag_id):
    """删除标签"""
    photo = Photo.query.get_or_404(photo_id)
    tag = Tag.query.get_or_404(tag_id)
    if current_user != photo.author:
        abort(403)

    # 这里只是删除图片与标签的关联，不会从数据库删除标签
    photo.tags.remove(tag)
    db.session.commit()

    # 如果标签不再与任何图片关联，则删除标签
    if not tag.photos:
        db.session.delete(tag)
        db.session.commit()

    flash('标签已删除', 'success')
    return redirect(url_for('main.show_photo', photo_id=photo.id))


@main_bp.route('/tag/<int:tag_id>', defaults={'order': 'by_time'})
@main_bp.route('/tag/<int:tag_id>/<order>')
def show_tag(tag_id, order):
    """展示标签"""
    tag = Tag.query.get_or_404(tag_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_PHOTO_PER_PAGE']
    pagination = Photo.query.with_parent(tag).order_by(Photo.timestamp.desc()).paginate(page, per_page)
    photos = pagination.items
    order_rule = '按时间排序'  # 排序规则

    if order == 'by_collects':
        photos.sort(key=lambda x: len(x.collectors), reverse=True)
        order_rule = '按收藏排序'
    return render_template('main/tag.html', tag=tag, photos=photos, pagination=pagination, order_rule=order_rule)


@main_bp.route('/report/comment/<int:comment_id>', methods=['POST'])
@login_required
@confirm_required
def report_comment(comment_id):
    """举报评论"""
    comment = Comment.query.get_or_404(comment_id)
    comment.flag += 1
    db.session.commit()
    flash('评论举报成功', 'success')
    return redirect(url_for('main.show_photo', photo_id=comment.photo_id))


@main_bp.route('/photo/<int:photo_id>/comment/new', methods=['POST'])
@login_required
@permission_required('COMMENT')
def new_comment(photo_id):
    """新建评论"""
    photo = Photo.query.get_or_404(photo_id)
    page = request.args.get('page', 1, type=int)
    form = CommentForm()
    if form.validate_on_submit():
        body = form.body.data
        author = current_user._get_current_object()
        comment = Comment(body=body, author=author, photo=photo)

        replied_id = request.args.get('reply')
        if replied_id:  # 如果得到参数'reply'，则说明是回复
            comment.replied = Comment.query.get_or_404(replied_id)
            if comment.replied.author.receive_comment_notification:
                push_comment_notification(photo_id=photo.id, receiver=comment.replied.author)
        db.session.add(comment)
        db.session.commit()
        flash('评论成功', 'success')

photosocial/templates/main/_photo_sidebar.html
{% from 'macros.html' import follow_area with context %}

<nav>
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link" href="{{ url_for('main.photo_previous',photo_id=photo.id) }}">&larr;上一页</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="{{ url_for('main.photo_next',photo_id=photo.id) }}">下一页&rarr;</a>
        </li>
    </ul>
</nav>
<div class="card bg-light mb-3 w-100 sidebar-card">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index',username=photo.author.username) }}">
                <img class="sidebar-avatar rounded avatar-m"
                     src="{{ url_for('main.get_avatar',filename=photo.author.avatar_m) }}">
            </a>
            <div class="sidebar-profile">
                <h6 class="card-title">
                    <a href="{{ url_for('user.index',username=photo.author.username) }}">{{ photo.author.name}}</a>
                </h6>
                <p class="card-subtitle mb-2 text-muted">{{ photo.author.username }}</p>
                {{ follow_area(photo.author) }}
            </div>
        </div>
    </div>
</div>

<div class="card bg-light mb-3 w-100">
    <div class="card-body">
        <div id="description">
            <p>
                {% if photo.description %}
                    {{ photo.description }}
                {% endif %}
                {% if current_user == photo.author %}
                    <a id="description-btn" href="#!">
                        <small><span class="oi oi-pencil"></span> 编辑图片描述</small>
                    </a>
                {% endif %}
            </p>
        </div>
        {% if current_user == photo.author %}
            <div id="description-form">
                <form action="{{ url_for('main.edit_description', photo_id=photo.id) }}" method="post">
                    {{ description_form.csrf_token }}
                    {{ render_field(description_form.description) }}
                    <a class="btn btn-light btn-sm" id="cancel-description">返回</a>
                    {{ render_field(description_form.submit, class='btn btn-success btn-sm') }}
                </form>
            </div>
        {% endif %}
        <div id="tags">
            <p>
                {% if photo.tags %}
                    {% for tag in photo.tags %}
                        <a class="badge badge-light"
                           href="{{ url_for('.show_tag', tag_id=tag.id) }}" target="_blank"><span
                                class="oi oi-tag"></span> {{ tag.name }}</a>
                    {% endfor %}
                {% endif %}
                {% if current_user == photo.author %}
                    <a id="tag-btn" href="#!">
                        <small><span class="oi oi-pencil"></span>编辑标签</small>
                    </a>
                {% endif %}
            </p>
        </div>
        {% if current_user == photo.author %}
            <div id="tag-form">
                <form action="{{ url_for('main.new_tag', photo_id=photo.id) }}" method="post">
                    {{ tag_form.csrf_token }}
                    {{ render_field(tag_form.tag) }}
                    <a class="btn btn-light btn-sm" id="cancel-tag">Cancel</a>
                    {{ render_field(tag_form.submit, class='btn btn-success btn-sm') }}
                </form>
                {% if photo.tags %}
                    <hr>
                    {% for tag in photo.tags %}
                        <a class="dead-link" href="#!"
                           data-href="{{ url_for('main.delete_tag', photo_id=photo.id, tag_id=tag.id) }}"
                           data-toggle="modal" data-target="#confirm-delete" title="Delete tag">
                        <span class="badge badge-danger">
                            {{ tag.name }} <span class="oi oi-trash" aria-hidden="true"></span>
                        </span>
                        </a>
                    {% endfor %}
                {% endif %}
            </div>
        {% endif %}
        <span class="btn-group" id="collect01">
            {% if current_user.is_authenticated %}
                <button class="{% if not current_user.is_collecting(photo) %}hide{% endif %}
                                    btn btn-outline-secondary btn-sm uncollect-btn"
                        data-href="{{ url_for('ajax.uncollect', photo_id=photo.id) }}"
                        data-id="{{ photo.id }}">
                    <span class="oi oi-x"></span> 取消收藏
                </button>
                <button class="{% if current_user.is_collecting(photo) %}hide{% endif %}
                                    btn btn-outline-primary btn-sm collect-btn"
                        data-href="{{ url_for('ajax.collect', photo_id=photo.id) }}"
                        data-id="{{ photo.id }}">
                    <span class="oi oi-heart"></span> 收藏
                </button>
            {% else %}
                <form class="inline" method="post" action="{{ url_for('main.collect',photo_id=photo.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button class="btn btn-info btn-sm">
                        <span class="oi oi-heart"></span> 收藏
                    </button>
                </form>
            {% endif %}
            {% if photo.collectors %}
                <a href="{{ url_for('main.show_collectors',photo_id=photo.id) }}">
                    <span class="btn btn-outline-success btn-sm" id="collectors-count-{{ photo.id }}"
                          data-href="{{ url_for('ajax.collectors_count',photo_id=photo.id) }}">
                        {{ photo.collectors|length }}
                    </span>
                </a>
            {% endif %}
        </span>
    </div>
</div>

photosocial/templates/main/_sidebar.html
<div class="card bg-light mb-3 w-100 sidebar-nav">
    <div class="card-body">
        <div class="row">
            <a href="{{ url_for('user.index',username=current_user.username) }}">
                <img class="rounded avatar-s" style="margin-left: 15px; position: absolute"
                     src="{{ url_for('main.get_avatar',filename=current_user.avatar_m) }}">
            </a>
            <div class="sidebar-nav-name">
                <h6 class="card-title">
                    <a href="{{ url_for('user.index',username=current_user.username) }}">{{ current_user.name }}</a>
                </h6>
                <p class="card-subtitle text-muted mb-2">{{ current_user.username }}</p>
            </div>
        </div>
        <a class="card-link" href="{{ url_for('user.index',username=current_user.username) }}">
            <span class="oi oi-home"></span> 我的图片
        </a><br>
        <a class="card-link" href="{{ url_for('user.show_collections',username=current_user.username) }}">
            <span class="oi oi-heart"></span> 我的收藏
        </a>
    </div>
</div>

<div class="card bg-light w-100 mb-3">
    <div class="card-header">热门标签</div>
    <div class="list-group">
        {% for tag in tags %}
            <a class="list-group-item" href="{{ url_for('main.show_tag',tag_id=tag.id) }}">
                {{ tag.name }}
                <span class="badge badge-pill badge-warning">{{  tag.photos|length }}</span>
            </a>
        {% endfor %}
    </div>
</div>

photosocial/templates/main/explore.html
{% extends 'base.html' %}
{% from 'macros.html' import photo_card with context%}

{% block title %}Explore{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% for photo in photos %}
                {{ photo_card(photo) }}
            {% endfor %}
        </div>
    </div>
    <div class="text-center">
        <a class="btn btn-outline-primary" href="{{ url_for('main.explore') }}">
            <span class="oi oi-loop-circular"></span>换一换
        </a>
    </div>
{% endblock %}

photosocial/templates/main/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card with context %}

{% block title %}Home{% endblock %}

{% block content %}
    {% if current_user.is_authenticated %}
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                {% if photos %}
                    {% for photo in photos %}
                        <div class="card mb-3 w-100 bg-light">
                            <div class="card-header">
                                <a class="dead-link" href="{{ url_for('user.index', username=photo.author.username) }}">
                                <img class="rounded img-fluid avatar-s profile-popover"
                                     data-href="{{ url_for('ajax.get_profile', user_id=photo.author.id) }}"
                                     src="{{ url_for('main.get_avatar', filename=photo.author.avatar_m) }}">
                                </a>
                                <a class="profile-popover trend-card-avatar"
                                   data-href="{{ url_for('ajax.get_profile', user_id=photo.author.id) }}"
                                   href="{{ url_for('user.index', username=photo.author.username) }}">
                                    {{ photo.author.name }}
                                </a>
                                <span class="float-right">
                                    <small data-toggle="tooltip" data-placement="top"
                                           data-timestamp="{{ photo.timestamp}}" data-delay="500">
                                        {{ moment(photo.timestamp).fromNow(refresh=True) }}
                                    </small>
                                </span>
                            </div>
                            <div class="card-body">
                                <div class="" align="center">
                                    <a class="thumbnail" href="{{ url_for('main.show_photo',photo_id=photo.id) }}"
                                       target="_blank">
                                        <img class="img-fluid"
                                             src="{{ url_for('main.get_image',filename=photo.filename_m) }}">
                                    </a>
                                </div>
                            </div>
                            <div class="card-footer index-card">
                                <a href="{{ url_for('main.show_collectors',photo_id=photo.id) }}">
                                    <span class="oi oi-heart"></span>
                                    <span id="collectors-count-{{ photo.id }}"
                                          data-href="{{ url_for('ajax.collectors_count',photo_id=photo.id) }}">
                                        {{ photo.collectors|length }}
                                    </span>
                                </a>&nbsp;&nbsp;
                                <a href="{{ url_for('main.show_photo',photo_id=photo.id) }}#comment">
                                    <span class="oi oi-comment-square"></span> {{ photo.comments|length }}
                                </a>
                                <div class="float-right">
                                    <button class="{% if not current_user.is_collecting(photo) %}hide{% endif %}
                                        btn btn-outline-secondary btn-sm uncollect-btn"
                                            data-href="{{ url_for('ajax.uncollect', photo_id=photo.id) }}"
                                            data-id="{{ photo.id }}">
                                        <span class="oi oi-x"></span> 取消收藏
                                    </button>
                                    <button class="{% if current_user.is_collecting(photo) %}hide{% endif %}
                                        btn btn-outline-primary btn-sm collect-btn"
                                            data-href="{{ url_for('ajax.collect', photo_id=photo.id) }}"
                                            data-id="{{ photo.id }}">
                                        <span class="oi oi-heart"></span> 收藏
                                    </button>
                                </div>
                                {% if photo.description %}
                                    <p class="card-text">{{ photo.description }}</p>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="tip text-center">
                        <h3>最近没有动态...</h3>
                        <p><a href="{{ url_for('main.explore') }}">去转转</a></p>
                    </div>
                {% endif %}
            </div>
            <div class="col-md-3">
                {% include 'main/_sidebar.html'%}
            </div>
        </div>
        {% if photos %}
            {{ render_pagination(pagination,align='center') }}
        {% endif %}
    {% else %}
        <div class="jumbotron">
            <div class="row">
                <div class="col-md-8">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="{{ url_for('static',filename='images/1.jpg') }}">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="{{ url_for('static',filename='images/2.jpg') }}">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="{{ url_for('static',filename='images/3.jpg') }}">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="{{ url_for('static',filename='images/4.jpg') }}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 align-self-center">
                    <h1>维度</h1>
                    <p>捕捉快乐的一瞬间，分享一瞬间的快乐！</p>
                    <p><a class="btn btn-primary btn-lg" href="{{ url_for('auth.register') }}">加入我们</a></p>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

photosocial/templates/main/profile_popup.html
<div class="popup-card">
    <img class="rounded img-fluid avatar-s popup-avatar"
         src="{{ url_for('main.get_avatar',filename=user.avatar_m) }}">
    <div class="popup-profile">
        <h6>{{ user.name }}</h6>
        <p class="text-muted">
            {{ user.username }}
            {% if current_user.is_authenticated %}
                {% if current_user != user and current_user.is_followed_by(user) %}
                    {% if user.is_followed_by(current_user) %}
                        <span class="badge badge-light">相互关注</span>
                    {% else %}
                        <span class="badge badge-light">关注了你</span>
                    {% endif %}
                {% endif %}
            {% endif %}
        </p>
    </div>

    <p class="card-text">
        <a href="{{ url_for('user.index',username=user.username) }}">
            <strong>{{ user.photos|length }}</strong> 图片
        </a>&nbsp;
        <a href="{{ url_for('user.show_followed',username=user.username) }}">
            <strong id="followers-count-{{ user.id }}"
                    data-href="{{ url_for('ajax.followers_count',user_id=user.id) }}">
                {{ user.followers.count()-1 }}
            </strong> 粉丝
        </a>
    </p>

    <a class="bt btn-light btn-sm" href="{{ url_for('user.index',username=user.username) }}">个人主页</a>
    {% if current_user.is_authenticated %}
        {% if user != current_user %}
            <button data-id="{{ user.id }}"
                    data-href="{{ url_for('ajax.unfollow',username=user.username) }}"
                    class="{% if not current_user.is_followed(user) %}hide{% endif %} btn btn-dark btn-sm unfollow-btn">
                取消关注
            </button>
            <button data-id="{{ user.id }}"
                    data-href="{{ url_for('ajax.follow',username=user.username) }}"
                    class="{% if current_user.is_followed(user) %}hide{% endif %} btn btn-primary btn-sm follow-btn">
                关注
            </button>
        {% endif %}
    {% else %}
        <form class="inline" method="post" action="{{ url_for('user.follow',username=user.username) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-primary btn-sm">关注</button>
        </form>
    {% endif %}
</div>