photosocial/blueprints/admin.py
import os

from flask import Blueprint, flash, render_template, redirect, url_for, request, current_app
from flask_login import login_required

from photosocial.extensions import db
from photosocial.models import User, Role, Tag, Photo, Comment
from photosocial.decorators import permission_required, admin_required
from photosocial.utils import redirect_back
from photosocial.forms.admin import EditProfileAdminForm

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/')
@login_required
@permission_required('MODERATE')
def index():
    photo_count = Photo.query.count()
    reported_photos_count = Photo.query.filter(Photo.flag > 0).count()
    user_count = User.query.count()
    locked_user_count = User.query.filter_by(locked=True).count()
    blocked_user_count = User.query.filter_by(active=False).count()
    tag_count = Tag.query.count()
    comment_count = Comment.query.count()
    reported_comments_count = Comment.query.filter(Comment.flag > 0).count()
    return render_template('admin/index.html', photo_count=photo_count, reported_photos_count=reported_photos_count,
                           user_count=user_count, locked_user_count=locked_user_count,
                           block_user_count=blocked_user_count, tag_count=tag_count, comment_count=comment_count,
                           reported_comments_count=reported_comments_count)


@admin_bp.route('/lock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def lock_user(user_id):
    """用户锁定"""
    user = User.query.get_or_404(user_id)
    user.lock()
    flash('该用户已锁定', 'info')
    return redirect_back()


@admin_bp.route('/unlock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unlock_user(user_id):
    """解除用户锁定"""
    user = User.query.get_or_404(user_id)
    user.unlock()
    flash('该用户锁定解除', 'info')
    return redirect_back()


@admin_bp.route('/block/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def block_user(user_id):
    """封禁用户"""
    user = User.query.get_or_404(user_id)
    user.block()
    flash('用户已封禁', 'info')
    return redirect_back()


@admin_bp.route('/unblock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unblock_user(user_id):
    """解除用户封禁"""
    user = User.query.get_or_404(user_id)
    user.unblock()
    flash('用户封禁已解除', 'info')
    return redirect_back()


@admin_bp.route('/profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(user_id):
    """管理员编辑用户资料"""
    user = User.query.get_or_404(user_id)
    form = EditProfileAdminForm(user=user)  # 传入被修改的用户对象作为参数
    if form.validate_on_submit():
        user.name = form.name.data
        role = Role.query.get(form.role.data)
        if role.name == 'Locked':
            user.lock()
        user.role = role
        user.username = form.username.data
        user.email = form.email.data
        user.website = form.website.data
        user.location = form.location.data
        user.bio = form.bio.data
        user.active = form.active.data
        user.confirmed = form.confirmed.data
        db.session.commit()
        flash('更新', 'success')
        return redirect_back()
    form.name.data = user.name
    form.role.data = user.role_id
    form.username.data = user.username
    form.email.data = user.email
    form.website.data = user.website
    form.location.data = user.location
    form.bio.data = user.bio
    form.active.data = user.active
    form.confirmed.data = user.confirmed
    return render_template('admin/edit_profile.html', form=form, user=user)


@admin_bp.route('/manage/photo', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/photo/<order>')
@login_required
@permission_required('MODERATE')
def manage_photo(order):
    """管理图片"""
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_MANAGE_PHOTO_PER_PAGE']
    order_rule = '被举报次数'
    if order == 'by_time':
        pagination = Photo.query.order_by(Photo.timestamp.desc()).paginate(page, per_page)
        order_rule = '时间'
    else:
        pagination = Photo.query.order_by(Photo.flag.desc()).paginate(page, per_page)
    photos = pagination.items
    return render_template('admin/manage_photo.html', photos=photos, pagination=pagination, order_rule=order_rule)


@admin_bp.route('/manage/user')
@login_required
@permission_required('MODERATE')
def manage_user():
    """管理用户"""
    filter_rule = request.args.get('filter', 'all')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_MANAGE_USER_PER_PAGE']
    moderator = Role.query.filter_by(name='Moderator').first()

    if filter_rule == 'locked':
        filtered_users = User.query.filter_by(locked=True)
    elif filter_rule == 'blocked':
        filtered_users = User.query.filter_by(active=False)
    elif filter_rule == 'moderator':
        filtered_users = User.query.filter_by(role=moderator)
    else:
        filtered_users = User.query

    pagination = filtered_users.order_by(User.member_since.desc()).paginate(page, per_page)
    users = pagination.items
    return render_template('admin/manage_user.html', pagination=pagination, users=users)


@admin_bp.route('/manage/tag')
@login_required
@permission_required('MODERATE')
def manage_tag():
    """管理标签"""
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_MANAGE_TAG_PER_PAGE']
    pagination = Tag.query.order_by(Tag.id.desc()).paginate(page, per_page)
    tags = pagination.items
    return render_template('admin/manage_tag.html', pagination=pagination, tags=tags)


@admin_bp.route('/delete/tag/<int:tag_id>', methods=['GET', 'POST'])
@login_required
@permission_required('MODERATE')
def delete_tag(tag_id):
    """删除标签"""
    tag = Tag.query.get_or_404(tag_id)
    db.session.delete(tag)
    db.session.commit()
    flash('Tag deleted.', 'info')
    return redirect_back()


@admin_bp.route('/manage/comment', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/comment/<order>')
@login_required
@permission_required('MODERATE')
def manage_comment(order):
    """管理评论"""
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['PHOTOSOCIAL_MANAGE_COMMENT_PER_PAGE']
    order_rule = '被举报次数'
    if order == 'by_time':
        pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(page, per_page)
        order_rule = '时间'
    else:
        pagination = Comment.query.order_by(Comment.flag.desc()).paginate(page, per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', pagination=pagination, order_rule=order_rule, comments=comments)

photosocial/blueprints/ajax.py
from flask import Blueprint, render_template, jsonify
from flask_login import current_user

from photosocial.models import User, Photo, Notification
from photosocial.notifications import push_collect_notification, push_follow_notification

ajax_bp = Blueprint('ajax', __name__)


@ajax_bp.route('/profile/<int:user_id>')
def get_profile(user_id):
    """返回用户资料"""
    user = User.query.get_or_404(user_id)
    return render_template('main/profile_popup.html', user=user)


@ajax_bp.route('/collectors-count/<int:photo_id>')
def collectors_count(photo_id):
    """图片收藏者数量"""
    photo = Photo.query.get_or_404(photo_id)
    count = len(photo.collectors)
    return jsonify(count=count)


@ajax_bp.route('/notifications-count')
def notifications_count():
    """未读消息数量"""
    if not current_user.is_authenticated:
        return jsonify(message='Login required.'), 403

    count = Notification.query.with_parent(current_user).filter_by(is_read=False).count()
    return jsonify(count=count)


@ajax_bp.route('/followers-count/<int:user_id>')
def followers_count(user_id):
    """粉丝数量"""
    user = User.query.get_or_404(user_id)
    count = user.followers.count() - 1  # 减去自己
    return jsonify(count=count)


@ajax_bp.route('/collect/<int:photo_id>', methods=['POST'])
def collect(photo_id):
    """收藏"""
    if not current_user.is_authenticated:
        return jsonify(message='请先登陆.'), 403
    if not current_user.confirmed:
        return jsonify(message='请先验证邮箱.'), 400
    if not current_user.can('COLLECT'):
        return jsonify(message='没有权限.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if current_user.is_collecting(photo):
        return jsonify(message='已经收藏过.'), 400

    current_user.collect(photo)
    if current_user != photo.author and photo.author.receive_collect_notification:
        push_collect_notification(collector=current_user, photo_id=photo_id, receiver=photo.author)
    return jsonify(message='收藏成功.')


@ajax_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
def uncollect(photo_id):
    """取消收藏"""
    if not current_user.is_authenticated:
        return jsonify(message='请先登陆.'), 403

    photo = Photo.query.get_or_404(photo_id)
    if not current_user.is_collecting(photo):
        return jsonify(message='没有收藏过.'), 400

    current_user.uncollect(photo)
    return jsonify(message='收藏取消.')


@ajax_bp.route('/follow/<username>', methods=['POST'])
def follow(username):
    """关注"""
    if not current_user.is_authenticated:
        return jsonify(message='请先登录.'), 403  # jsonify生成json相应格式，并返回提示消息
    if not current_user.confirmed:
        return jsonify(message='请先验证邮箱.'), 400
    if not current_user.can('FOLLOW'):
        return jsonify(message='没有权限.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_followed(user):
        return jsonify(message='已经关注过.'), 400

    current_user.follow(user)
    if user.receive_collect_notification:
        push_follow_notification(follower=current_user, receiver=user)
    return jsonify(message='关注成功.')


@ajax_bp.route('/unfollow/<username>', methods=['POST'])
def unfollow(username):
    """取消关注"""
    if not current_user.is_authenticated:
        return jsonify(message='请先登陆.'), 403

    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_followed(user):
        return jsonify(message='还没有关注他/她.'), 400

    current_user.unfollow(user)
    return jsonify(message='关注取消.')

photosocial/blueprints/auth.py
from flask import Blueprint, redirect, url_for, flash, render_template
from flask_login import current_user, login_required, login_user, logout_user, login_fresh, confirm_login

from photosocial.emails import send_confirm_email, send_reset_password_email
from photosocial.forms.auth import RegisterForm, LoginForm, ForgetPasswordForm, ResetPasswordForm
from photosocial.models import User
from photosocial.extensions import db
from photosocial.utils import generate_token, validate_token, redirect_back
from photosocial.settings import Operations

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('登陆成功.', 'info')
                return redirect_back()
            else:
                flash('您的帐户被封禁了.', 'warning')
                return redirect(url_for('main.index'))
        flash('无效的邮箱或者密码.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('登出成功', 'success')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data.lower()  # 使用小写,避免同一个邮箱使用不同大小写注册
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()

        token = generate_token(user=user, operation='confirm')  # 创建令牌
        send_confirm_email(user=user, token=token)  # 发送验证邮件
        flash('验证邮件已发送，请检查你的收件箱', 'info')
        return redirect(url_for('auth.login'))
    return render_template('auth/register.html', form=form)


@auth_bp.route('/confirm/<token>')
@login_required  # login_required 装饰器确保只有登陆的用户才可以访问对应的资源
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('main.index'))

    if validate_token(user=current_user, token=token, operation=Operations.CONFIRM):
        flash('帐户认证成功', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('无效或过期令牌', 'danger')
        return redirect(url_for('auth.resend_confirm_email'))  # 验证没通过,重定向到发送验证邮件的视图


@auth_bp.route('/resend-confirm-email')
@login_required
def resend_confirm_email():
    """发送验证邮件"""
    if current_user.cofirmed:
        return redirect(url_for('main.index'))

    token = generate_token(user=current_user, operation=Operations.CONFIRM)
    send_confirm_email(user=current_user, token=token)
    flash('新邮件已发送，请检查收件箱', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/forget-password', methods=['POST', 'GET'])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash('密码重置邮件已发送，请检查您的收件箱', 'info')
            return redirect(url_for('auth.login'))
        flash('无效邮件', 'warning')
        return redirect(url_for('auth.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ResetPasswordForm()
    if form.validate_on_submit():  # 如果表单提交
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is None:  # 判断这个邮箱是否存在
            return redirect(url_for('main.index'))

        if validate_token(user=user, token=token,
                          operation=Operations.RESET_PASSWORD, new_password=form.password.data):
            flash('密码已重置', 'success')
            return redirect(url_for('auth.login'))
        else:
            flash('无效或过期链接', 'danger')
            return redirect(url_for('auth.forget_password'))
    return render_template('auth/reset_password.html', form=form)


@auth_bp.route('/re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    """当用户‘不新鲜’时访问带@fresh_login_required的视图时，重新认证"""
    if login_fresh():
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        confirm_login()
        return redirect_back()
    return render_template('auth/login.html', form=form)

photosocial/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
        <title>{% block title %}{% endblock %} - PhotoSocial</title>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {% block style %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
            <link rel="stylesheet"
                  href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        {% endblock %}
    {% endblock %}
</head>
<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index')}}">
                <img src="{{ url_for('static',filename='favicon.ico') }}" alt="图片社交网">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="#navbarColor01">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('main.index','主页') }}
                    {{ render_nav_item('main.explore','发现') }}
                    <form class="form-inline" action="{{ url_for('main.search') }}">
                        <input type="text" name="q" class="form-control mr-sm-1" placeholder="图片、标签或用户"
                               required>
                        <button class="btn btn-light">
                            <span class="oi oi-magnifying-glass"></span>
                        </button>
                    </form>
                </div>
                <div class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('main.show_notifications', filter='unread') }}">
                            <span class="oi oi-bell"></span>
                            <span id="notification-badge"
                                  class="{% if notification_count==0 %}hide{% endif %} badge badge-danger badge-notification"
                                  data-href="{{ url_for('ajax.notifications_count') }}">
                                {{ notification_count }}
                            </span>
                        </a>
                        <a class="nav-item nav-link" href="{{ url_for('main.upload') }}" title="上传">
                            <span class="oi oi-cloud-upload"></span>&nbsp;&nbsp;&nbsp;
                        </a>
                        <div class="dropdown nav-item">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                                <img class="avatar-xs"
                                     src="{{ url_for('main.get_avatar', filename=current_user.avatar_s) }}">
                                <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <h6 class="dropdown-header">用户：{{ current_user.username }}</h6>
                                <a class="dropdown-item"
                                   href="{{ url_for('user.index', username=current_user.username,candelete='photo') }}">
                                    <span class="oi oi-person"></span> 我的
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ url_for('user.edit_profile') }}">
                                    <span class="oi oi-cog"></span> 设置
                                </a>
                                {% if current_user.can('MODERATE') %}
                                    <a class="dropdown-item" href="{{ url_for('admin.index') }}">
                                        <span class="oi oi-dashboard"></span> 管理
                                    </a>
                                {% endif %}
                                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                    <span class="oi oi-power-standby"></span> 登出
                                </a>
                            </div>
                        </div>
                    {% else %}
                        <a class="btn btn-outline-primary" href="{{ url_for('auth.login') }}">登陆</a>&nbsp;&nbsp;
                        <a class="btn btn-primary" href="{{ url_for('auth.register') }}">加入我们</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
{% endblock %}

<main>
    <div class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}
        {% block content %}{% endblock %}
        {% block footer %}
            <footer>
                <p class="float-left">
                    <small>&copy;2018 -
                        <a href="{{ url_for('main.index') }}">维度</a> - 基于Python Flask -
                        <a href="https://github.com/gweid">GitHub</a>
                    </small>
                </p>
                <p class="float-right">
                    <small>维度，捕捉快乐的一瞬间，分享一瞬间的快乐</small>
                </p>
            </footer>
        {% endblock %}
    </div>
</main>
<div id="toast"></div>

{% block script %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    {{ moment.locale('zh-cn') }}
    <script src="{{ url_for('static',filename='js/script.js') }}"></script>
    <script type="text/javascript">
        var csrf_token = "{{ csrf_token() }}";
        {% if current_user.is_authenticated %}
            var is_authenticated = true;
        {% else %}
            var is_authenticated = false;
        {% endif %}
    </script>
{% endblock %}
</body>
</html>

photosocial/templates/macros.html
{% macro photo_card(photo) %}
    <div class="photo-card card">
        <a class="card-thumbnail" href="{{ url_for('main.show_photo', photo_id=photo.id) }}">
            <img class="card-img-top portrait" src="{{ url_for('main.get_image', filename=photo.filename_s) }}">
        </a>
        <div class="card-body">
            <span class="oi oi-star"></span> {{ photo.collectors|length }}
            <span class="oi oi-comment-square"></span> {{ photo.comments|length }}
            {% if request.args.get('candelete')=='collect' %}
                <form class="inline" method="post" action="{{ url_for('main.uncollect',photo_id=photo.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button class="btn btn-link btn-md user_collect_btn" onclick="return confirm('确定取消收藏吗');">
                        <span class="oi oi-trash"></span>
                    </button>
                </form>
            {% endif %}
            {% if request.args.get('candelete')=='photo' %}
                <form class="inline" method="post" action="{{ url_for('main.delete_photo',photo_id=photo.id,candelete='photo') }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button class="btn btn-link btn-md user_collect_btn" onclick="return confirm('确定删除吗');">
                        <span class="oi oi-trash"></span>
                    </button>
                </form>
            {% endif %}
        </div>
    </div>
{% endmacro %}

<!--用户资料弹窗-->
{% macro user_card(user) %}
    <div class="user-card text-center">
        <a href="{{ url_for('user.index',username=user.username) }}">
            <img class="rounded avatar_m" src="{{ url_for('main.get_avatar',filename=user.avatar_m) }}">
        </a>
        <h6>
            <a href="{{ url_for('user.index',username=user.username) }}">{{ user.name }}</a>
        </h6>
        {{ follow_area(user) }}
    </div>
{% endmacro %}

<!--关注-->
{% macro follow_area(user) %}
    {% if current_user.is_authenticated %}
        {% if user != current_user %}  <!--不对用户自己显示关注按钮-->
            {% if current_user.is_followed(user) %}  <!--当前用户正在关注该用户是显示取消关注按钮-->
                <form class="inline" method="post"
                      action="{{ url_for('user.unfollow',username=user.username,next=request.full_path) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-dark btn-sm">
                        取消关注
                    </button>
                    {% if current_user.is_followed_by(user) %}  <!--如果当前用户同时被该用户关注，则显示互相关注-->
                        <p class="badge badge-light">互相关注</p>
                    {% endif %}
                </form>
            {% else %}
                <form class="inline" method="post"
                      action="{{ url_for('user.follow',username=user.username,next=request.full_path) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-primary btn-sm">
                        关注
                    </button>
                    {% if current_user.is_followed_by(user) %}  <!--如果该用户关注了拟则显示关注了你-->
                        <p class="badge badge-light">关注了你</p>
                    {% endif %}
                </form>
            {% endif %}
        {% endif %}
    {% else %} <!--如果用户没有登陆-->
        <form class="inline" method="post" action="{{ url_for('user.follow',username=user.username) }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-primary btn-sm">
                关注
            </button>
        </form>
    {% endif %}
{% endmacro %}